version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/99
permissions:
   - object: /var/www/99
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file